apiVersion: apps/v1beta2
kind: Deployment
metadata: 
  name: guestbook-api-deployment
  namespace: guestbook-ns
  labels: 
    app: guestbook-api
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: guestbook-api
  template: 
    metadata: 
      labels:
        app: guestbook-api
    spec: 
      containers:
      - name: guestbook-api
        image: remkohdev/guestbook-api:1.0.0
        ports:
        - name: main
          protocol: TCP
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: guestbook-api-configmap
        resources:
          requests:
            memory: "120M"
            cpu: "500m"