apiVersion: v1
kind: Service
metadata:
  name: guestbook-api-svc
  namespace: guestbook-ns
  labels:
    app: guestbook-api
spec:
  type: NodePort
  ports:
  - name: main
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector: 
    app: guestbook-api